### ISSUE TITLE
[PE-D] Adding transaction for members

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#139]
I have a list of members, but when I try to add a transaction, based on your UG, I get an error message. 
![Screenshot 2021-10-29 at 4.39.43 PM.png](https://raw.githubusercontent.com/itsraveen/ped/main/files/958aa70f-dd3e-4856-94fd-1e9bca1a953b.png)

![Screenshot 2021-10-29 at 4.39.57 PM.png](https://raw.githubusercontent.com/itsraveen/ped/main/files/ff95180a-eb00-4cb5-89fc-8a237239cb2d.png)

As a result I am unable to proceed with the adding of transactions. 

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: itsraveen/ped#6

**Comment by zzybluebell** [comment]
update ug for add txn
