### ISSUE TITLE
[PE-D] Member already exists

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#142]
If you have some duplicate entries and try to add more, it shows you member already exists. I tested that the only parameters that does not allow duplicates is email and phone. I think it would be better if this was mentioned somewhere. 

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: yin72257/ped#5

**Comment by zzybluebell** [comment]
update ug
