### ISSUE TITLE
[PE-D] Login Feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#143]
I am unclear on how this login works. Is the password fixed? And can there be multiple managers? Also the password does not look very secure, seems a bit too easy to crack. 
![Screenshot 2021-10-29 at 4.44.14 PM.png](https://raw.githubusercontent.com/itsraveen/ped/main/files/17c755c1-8eb9-435f-9fee-47b713d363ea.png)

Again, might want to check if you product meets the module tP constrains which I included in the previous bug issues.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: itsraveen/ped#7

**Comment by zzybluebell** [comment]
same issues with #175

**Comment by HolmesJJ** [comment]
Update UG
