### ISSUE TITLE
[PE-D] Phone Number Issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#146]
You requirement for phone number is only 3. Might want to make this better as many phone numbers are longer than 3. 
![Screenshot 2021-10-29 at 4.47.31 PM.png](https://raw.githubusercontent.com/itsraveen/ped/main/files/b09a33cd-0ae1-4c90-a411-bce7aa4d46fe.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: itsraveen/ped#8

**Comment by zzybluebell** [comment]
bug with phone number format
