### ISSUE TITLE
[PE-D] [UG] Wrong command in summary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#151]
I believe this should be `list -mem`

![image.png](https://raw.githubusercontent.com/VimuthM/ped/main/files/de3ef8bc-028d-42c1-9c91-a53c180d13e2.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: VimuthM/ped#9

**Comment by zzybluebell** [comment]
update UG！
