### ISSUE TITLE
[PE-D] [Bug] Edit txn does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#153]
I cannot edit the transaction field

Steps to reproduce: 

 - Run `edit -mem -row 1 -txn 123.45`

Expected: 

 - Successful edit

Actual: 

![image.png](https://raw.githubusercontent.com/VimuthM/ped/main/files/4d942629-6b21-42e7-a935-61233d5af115.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: VimuthM/ped#10

**Comment by HolmesJJ** [comment]
Update the flow of edit and UG
