### ISSUE TITLE
[PE-D] [Feat] Use of -mem

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#154]
Most commands require this flag to be present but since there's no other model in use, it might be redundant and just increase command length.

This is just an opinion, feel free to discuss!

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: VimuthM/ped#11

**Comment by HolmesJJ** [comment]
Not redundant? Need to check the logic first
