### ISSUE TITLE
[PE-D] ID considered not having 5 digits even when it has exactly 5

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#161]
![Screenshot 2021-10-29 231706.png](https://raw.githubusercontent.com/kawaiigabrielneko/ped/main/files/d1f71838-59c4-4c38-9ebc-b5d75e846c2e.png)

This command is in the format of the UG, and yet it still parses as an error, even though id=10007 is present.

This command seems to fail when the person has no transactions. 

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kawaiigabrielneko/ped#6

**Comment by HolmesJJ** [comment]
Fix bug
