### ISSUE TITLE
[PE-D] While logged out, list remains sorted by credit, even when updated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#162]
Steps to replicate:

* Start an address book with at least two people having different credit
* Log in as manager
* Sort by credit in descending order
* Log out

The list is still sorted by credit, which is unexpected since the sort function is restricted to managers. 

Furthermore, if a transaction is added to a customer, which would bring them up in the list due to overtaking others in credit, they would do so, even though the list should no longer be sorted by credit. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kawaiigabrielneko/ped#7

**Comment by HolmesJJ** [comment]
Fix bug
