### ISSUE TITLE
[PE-D] Date format wrong in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#171]
![Screenshot 2021-10-29 234442.png](https://raw.githubusercontent.com/kawaiigabrielneko/ped/main/files/fa30f9cb-89a8-409d-b003-4e6968da4b32.png)

The UG suggests dates are input in DD-MM-YYYY format. However, finding `02-01-2021` yields no results in ezFoodie, while `2021-01-02` yields 6 results. 

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: kawaiigabrielneko/ped#16

**Comment by HolmesJJ** [comment]
Update UG

**Comment by Morrow1ndy** [comment]
Will update UG.
