### ISSUE TITLE
[PE-D] Hidden "Membership Level" statistic not mentioned. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#172]
After each person's name, there appears to be a "membership level", i.e. `Bronze, Silver, Gold, Platinum`. However, I did not find this in the UG, and this got me confused as I interpreted it as part of the person's name. 

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: kawaiigabrielneko/ped#17

**Comment by HolmesJJ** [comment]
Update the UG

**Comment by zzybluebell** [comment]
UG indication？
Update

**Comment by Morrow1ndy** [comment]
Will update UG.
