### ISSUE TITLE
[PE-D] Listing all members

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#174]
So this is my list of members: 

![Screenshot 2021-10-29 at 4.32.22 PM.png](https://raw.githubusercontent.com/itsraveen/ped/main/files/0a75d398-bd07-459b-8e12-fa365882d689.png)

When I enter the command "find -mem -id 00000"

I get this: 

![Screenshot 2021-10-29 at 4.32.48 PM.png](https://raw.githubusercontent.com/itsraveen/ped/main/files/09539d19-c902-43ef-8314-8983390228c2.png)

I think since your members ids are automatically starts from 1, perhaps will be nice if user gets an error message for searching 00000. I guess this implementation is not wrong, but I think the error message will improve the overall experience. 

Likewise when my entered id is > total list length, I get 0 members. Same comment as above!

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: itsraveen/ped#4

**Comment by HolmesJJ** [comment]
Not a bug?
Id not equal to Index
Can indicate in the UG start from 1 if necessary

**Comment by Morrow1ndy** [comment]
I think this issue is not related to index.
Will indicate the expected behaviour when an invalid member id in typed.
