### ISSUE TITLE
[PE-D] Login feature hard to test

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-4/tp#175]
The program was hard to test because it had a "login" section, and a password was not provided. This made it hard to test the program, as several features required logging in; I was only able to do so because the password happened to be the same as the one in the UG.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: kawaiigabrielneko/ped#3

**Comment by HolmesJJ** [comment]
1. Privode the password to UG
2. Fix the flow of password logic?... Like the user can update the password

**Comment by HolmesJJ** [comment]
Bug fixed

**Comment by zzybluebell** [comment]
password provided in UG
